version: "3.9"
services:
  # Start web-app in development
  # docker-compose -f docker-compose.yml -f docker-compose.web-app.yml up main-db develop
  develop:
    container_name: nextjs-app-develop
    stdin_open: true
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
    volumes:
      # Share the source code to allow development
      - .:/app/
      # Prevent sharing of node_modules between host and container
      # to avoid ownership and/or platform issues
      - nm_react-next-app:/app/examples/react-next/node_modules
      - nm_monorepo:/app/node_modules
      - nm_react-package:/app/packages/react/node_modules

volumes:
  nm_react-next-app:
  nm_monorepo:
  nm_react-package:
