name: "CI setup"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: "yarn"

    - name: Install Dependencies
      run: yarn --immutable
      shell: bash

    - name: Build packages
      run: yarn packages:build
      shell: bash
